config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :veterinarians do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'
  get 'pages/contact'
  root "veterinarians#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :Veterinarian, optional: true

  validates :rating, :comment, presence: true

  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: "must be a whole number between 1 and 5"
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/models/veterinarian.rb
class Veterinarian < ApplicationRecord
  mount_uploader :image, ImageUploader

  searchkick
  
  has_many :reviews

  validates :name, :address, :phone, :website, presence: true

  validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
    message: "must be in the format (123) 456-7890" }

    validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
      message: "must start with http:// or https://" }

    validates :address, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
      message: "must be in the format: 350 Fifth Avenue, New York, NY 10118" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_veterinarian
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.veterinarian_id = @veterinarian.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to veterinarian_path(@veterinarian), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to veterinarian_path(@veterinarian), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_veterinarian
      @veterinarian = Veterinarian.find(params[:veterinarian_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to another user"
      end
    end

end

app/controllers/veterinarians_controller.rb
class VeterinariansController < ApplicationController
  before_action :set_veterinarian, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]

  # GET /veterinarians
  # GET /veterinarians.json
  def index
    @veterinarians = Veterinarian.all.paginate(page: params[:page], per_page: 10)
end

  def search
    if params[:search].present?
      @veterinarians = Veterinarian.search(params[:search])
    else
      @veterinarians = Veterinarian.all
    end
  end

  # GET /veterinarians/1
  # GET /veterinarians/1.json
  def show
    @reviews=Review.where(veterinarian_id: @veterinarian.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else @avg_rating = @reviews.average(:rating).round(3)
    end
  end

  # GET /veterinarians/new
  def new
    @veterinarian = Veterinarian.new
  end

  # GET /veterinarians/1/edit
  def edit
  end

  # POST /veterinarians
  # POST /veterinarians.json
  def create
    @veterinarian = Veterinarian.new(veterinarian_params)

    respond_to do |format|
      if @veterinarian.save
        format.html { redirect_to @veterinarian, notice: 'Veterinarian was successfully created.' }
        format.json { render :show, status: :created, location: @veterinarian }
      else
        format.html { render :new }
        format.json { render json: @veterinarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veterinarians/1
  # PATCH/PUT /veterinarians/1.json
  def update
    respond_to do |format|
      if @veterinarian.update(veterinarian_params)
        format.html { redirect_to @veterinarian, notice: 'Veterinarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @veterinarian }
      else
        format.html { render :edit }
        format.json { render json: @veterinarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veterinarians/1
  # DELETE /veterinarians/1.json
  def destroy
    @veterinarian.destroy
    respond_to do |format|
      format.html { redirect_to veterinarians_url, notice: 'Veterinarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veterinarian
      @veterinarian = Veterinarian.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def veterinarian_params
      params.require(:veterinarian).permit(:name, :address, :phone, :website, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/veterinarians_helper.rb
module VeterinariansHelper
end

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

<!-- latest minified jquery, 2019 02 13 -->
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<div style="position:relative; bottom: 0; text-align: center; width: 98%; font-size: 12px;">
<p style="text-align:center">Copyright 2020 Vetspotter</p>
</div>

app/views/layouts/_navbar.html.erb
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">VETSPOTTER</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button> -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light"><%= link_to "VETSPOTTER", root_path, class: "navbar-brand" %>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <!-- modified 2019 01 26
  <li class="nav-item">
    <a class="nav-link" href="/pages/about">About<span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/pages/contact">Contact</a>
  </li> -->
<ul class="navbar-nav mr-auto">
  <li class="nav-item"><%= link_to "About", pages_about_path, class: "nav-link" %></li>
  <li class="nav-item"><%= link_to "Contact", pages_contact_path, class: "nav-link" %></li>
</ul>
<ul class= "nav navbar-nav navbar-right">
  <% if user_signed_in? %>
  <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
  <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
  <% else %>
  <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
  <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
  <% end %>
</ul>


<!-- OLD Search form, removed 2019 03 23
<form class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
-->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vetspotter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/bootstrap' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class= "container-fluid">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>

      <% unless action_name == "index" or "about" %> <%=render 'layouts/footer' %> <% end %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron" style="background-color: #8fd2ff;">

<h1 style="margin-top:100px; font-weight:200;">Welcome to Vetspotter</h1>
<br>
<p style="margin-right:300px; margin-left:300px; margin-bottom:250px">We love our pets--and in order to give them the best life that we can, we need to be mindful about the cost of caring for them.  Let's work together so that we know what we're getting, when we need veterinary care</p>

</div>

<div style="position:absolute; bottom: 0; text-align: center; width: 98%; font-size: 12px;">
<p style="text-align:center">Copyright 2020 Vetspotter</p>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron" style="background-color: #8fd2ff;">

<h1 style="margin-top:100px; font-weight:200;">We would love to hear from you</h1>
<br>
<p style="text-align: center; margin-right:300px; margin-left:300px; margin-bottom:250px">Contact us at: editor@vetspotter.com</p>

</div>

<div style="position:absolute; bottom: 0; text-align: center; width: 98%; font-size: 12px;">
<p style="text-align:center">Copyright 2020 Vetspotter</p>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@veterinarian, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      <h4><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p style="font-size: 15px;"> Overall rating on a scale of 1-5:</p>
  <div style="margin-bottom: 0px;" id="star-rating"> </div>
  <br>

  <div style="margin-top: -10px; class="form-group">
  <p style="font-size: 15px;"> <%= form.label :comment  %>: </p>
  <p>  <%= form.text_area :comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
$('#star-rating').raty({
  path: 'https://s3.amazonaws.com/vetspotter/stars',
  scoreName: 'review[rating]'
});
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', veterinarian_path(@veterinarian) %>

app/views/reviews/new.html.erb
<div style="min-height:100%;">
<h1 style="margin-top: 10px;">New Review</h1>
<h2 style="text-align:center;"><%= @veterinarian.name %> <h2>

<br>

<div class = "row">
<div class="col col-lg-6" style="padding-right:150px;">

<%= render 'form', review: @review %>

<span style="font-size:15px;"> <%= link_to 'Back', veterinarian_path(@veterinarian) %></span>


</div>

<div>

<div class="col col-lg-6">

<div style="margin-left:175px;">
<%= image_tag @veterinarian.image_url %>
</div>

</div>

</div>

</div>

app/views/veterinarians/_form.html.erb
<%= form_with(model: veterinarian, local: true, :html => {multipart:true}) do |form| %>
  <% if veterinarian.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(veterinarian.errors.count, "error") %> prohibited this veterinarian from being saved:</h4>

      <ul>
      <% veterinarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control", placeholder: "350 Fifth Avenue, New York, NY 10118" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control", placeholder: "(123) 456-7890" %>
  </div>

  <div class="form-group">
    <%= form.label :website %>
    <%= form.text_field :website, class: "form-control", placeholder: "http://www.coldlightofdog.com" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

<br>
  <div class="actions">
      <%= form.submit class: "btn btn-primary"%>
  </div>

<% end %>

app/views/veterinarians/edit.html.erb
<h1>Editing Veterinarian</h1>

<%= render 'form', veterinarian: @veterinarian %>

<%= link_to 'Show', @veterinarian, class: "btn btn-link" %> |
<%= link_to 'Back', veterinarians_path, class: "btn btn-link" %>

app/views/veterinarians/index.html.erb
<!--

<p id="notice"><%= notice %></p>

accommodating custom alerts; br added below 2019 02 13-->


<br>

<div class="jumbotron text-center">
  <h2 style="color:black; font-weight:200;">Search Vetspotter to find reviews of local veterinarians</h2>
  <br>
  <!--search bar and button width/alignment are messy, need to be fixed when I understand it. 20190630-->
  <div class="example form-inline", style="width:51%; margin-right:auto; margin-left:auto;">
  <%= form_tag search_veterinarians_path, method: :get do %>
    <p>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Enter address, city, or zip', style:"width:600px;"%>
      <!-- can't figure out why this doesn't work, 2019 03 25 <i class= "glyphicon glyphicon-search" ></i> -->
      <%= submit_tag "Search", style: "color:white;", name: nil, class: "btn btn-front_page" %>
    </p>
    <% end %>
    </div>
</div>

<div class="row">
<div class="col col-lg-6">
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location and Contact</th>
      <th>Average User Rating</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @veterinarians.each do |veterinarian|
    @reviews = Review.where(veterinarian_id:veterinarian.id)
    @avg_rating = @reviews.average(:rating)%>

      <tr>
        <td col width="140"><%=  link_to veterinarian.name, veterinarian %></td>
        <td><%= veterinarian.address %> <br> <%= veterinarian.phone %> <br> <%= link_to veterinarian.website, veterinarian.website %></td>

      <td col width="200px"><p class="star-rating" data-score= <%= @avg_rating %></p> <p><%= "Average from #{@reviews.length} reviews" %></p></td>

        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_veterinarian_path(veterinarian), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', veterinarian, class: "btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col col-lg-6 text-center">
<!--
  <iframe
    width="400"
    height="400"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3104.2110814013613!2d-77.03848538503253!3d38.91915265326718!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89b7b7dc5cadbdd3%3A0x99752a7d2ae4f853!2sWashington%2C+DC+20009!5e0!3m2!1sen!2sus!4v1562114263530!5m2!1sen!2sus"
  </iframe>
-->




</div>

</div>



<% if user_signed_in? && current_user.admin? %>
<%= link_to 'New Veterinarian', new_veterinarian_path, class: "btn btn-link" %>
<% end %>
<br>
<br>
<div class="bottom_image" style="margin-bottom: 10px;">
<%= image_tag('https://s3.amazonaws.com/vetspotter/tom-Waiting-dog-lineart.png', :size=> "75x75", :alt=> "sitting dog logo") %>
<p style="text-align: center; width: 100%; font-size: 12px">Copyright 2020 Vetspotter</p>
</div>

<script>
$('.star-rating').raty('destroy');
$('.star-rating').raty({
  path: 'https://s3.amazonaws.com/vetspotter/stars',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>

app/views/veterinarians/new.html.erb
<h1>New Veterinarian</h1>

<%= render 'form', veterinarian: @veterinarian %>

<%= link_to 'Back', veterinarians_path, class: "btn btn-link" %>

app/views/veterinarians/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @veterinarians.each do |veterinarian| %>
      <tr>
        <td><%= link_to veterinarian.name, veterinarian %></td>
        <td><%= veterinarian.address %></td>
        <td><%= veterinarian.phone %></td>
        <td><%= link_to veterinarian.website, veterinarian.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_veterinarian_path(veterinarian), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', veterinarian, class: "btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @veterinarians, renderer: BootstrapPagination::Rails %>

app/views/veterinarians/show.html.erb
<br><br>
<div class = "row">
  <div class = "col-md-3">
    <%= image_tag @veterinarian.image_url %>

    <h2>
      <%= @veterinarian.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "Average from #{@reviews.length} reviews" %></p>

    <p>
      <strong>Address:</strong>
      <%= @veterinarian.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @veterinarian.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @veterinarian.website, @veterinarian.website %>
    </p>
    <br>
    <%= link_to "Write a Review", new_veterinarian_review_path(@veterinarian), class: "btn" %>
    <br>
    <br>
    <iframe
      width="300"
      height="300"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyACHabXbdUZmjzuBcoN-fHwA-IHJnLlyTA
        &q=<%= @veterinarian.address.parameterize %>&zoom=12" allowfullscreen>
    </iframe>
  </div>

  <div class = "col-md-9" style="background-color: #f7f7f7">

    <% if @reviews.blank? %>
    <br>
    <h3>No reviews yet.  Be the first to write one!</h3>
    <% else %>

    <table class = "table review-table">
      <!--this column width bit is super hacky, should probably be fixed -->
      <thead>
        <tr>
          <th width=100px></th>
          <th width=full></th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td>
            <h4>
              <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}" %>
            </h4>
            <p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
            </td>

           <td>
            <div class="star-rating" data-score= <%= review.rating %> ></div>
            <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
            <% if user_signed_in? %>
            <% if (review.user == current_user) || (current_user.admin?) %>
                <%= link_to "Edit", edit_veterinarian_review_path(@veterinarian, review) %>
                <%= link_to "Delete", veterinarian_review_path(@veterinarian, review), method: :delete %>
                <% end %>
                <% end %>
          </td>

          </tr>
        <% end %>
      </tbody>
    </table>

    <% end %>
  </div>
</div>


<br>
<div style=text-align:center;>
<%= link_to 'Edit', edit_veterinarian_path(@veterinarian), class: "btn" %> |
<%= link_to 'Back', veterinarians_path, class: "btn" %>
</div>
<br>

<script>
$('.star-rating').raty('destroy');
$('.star-rating').raty({
  path: 'https://s3.amazonaws.com/vetspotter/stars',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>